name: Build and Release Icecap Agent

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -A Win32

      - name: Build
        run: cmake --build build --target icecap-agent --config Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: icecap-agent-dll
          path: build/Release/icecap-agent.dll

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/Release/icecap-agent.dll
          generate_release_notes: true
